name: flutter_useragent
description: Retrieve Android/iOS device user agents in Flutter.
version: 1.0.0
homepage: https://github.com/TheGlorySaint/flutter_useragent

environment:
  sdk: ">=3.1.2 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

# The following section is specific to Flutter.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' and Android 'package' identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: io.theglorysaint.flutter_useragent
        pluginClass: FlutterUserAgentPlugin 
      ios:
        pluginClass: FlutterUserAgentPlugin 
